### ISSUE TITLE
Could not install with VS 2019 Community (v16.2.1)

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan-vs-extension#161]
Visual Studio 16.2.1 (Community)
Used the nightly: 8aa88c3eddea811df893ac8b1b1c2039556ab1fb (but same with the released one)
```
07/08/2019 14:25:19 - Microsoft VSIX Installer
07/08/2019 14:25:19 - -------------------------------------------
07/08/2019 14:25:19 - vsixinstaller.exe version:
07/08/2019 14:25:19 - 16.3.27-develop-g3fc576ad
07/08/2019 14:25:19 - -------------------------------------------
07/08/2019 14:25:19 - Command line parameters:
07/08/2019 14:25:19 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Conan.VisualStudio.vsix
07/08/2019 14:25:19 - -------------------------------------------
07/08/2019 14:25:19 - Microsoft VSIX Installer
07/08/2019 14:25:19 - -------------------------------------------
07/08/2019 14:25:19 - Initializing Install...
07/08/2019 14:25:19 - Extension Details...
07/08/2019 14:25:19 - 	Identifier         : VSConanPackage.4d0379e2-2698-4e66-89de-6ead71165e9f
07/08/2019 14:25:19 - 	Name               : Conan Extension for Visual Studio
07/08/2019 14:25:19 - 	Author             : Conan
07/08/2019 14:25:19 - 	Version            : 1.2.0.268
07/08/2019 14:25:19 - 	Description        : Conan Extension for Visual Studio automates the use of the Conan C/C++ package manager for retrieving dependencies within Visual Studio projects.
07/08/2019 14:25:19 - 	Locale             : en-US
07/08/2019 14:25:19 - 	MoreInfoURL        : https://github.com/conan-io/conan-vs-extension
07/08/2019 14:25:19 - 	InstalledByMSI     : False
07/08/2019 14:25:19 - 	SupportedFrameworkVersionRange : [4.5,)
07/08/2019 14:25:19 - 
07/08/2019 14:25:19 - 	SignatureState     : Unsigned
07/08/2019 14:25:19 - 	Supported Products : 
07/08/2019 14:25:19 - 		Microsoft.VisualStudio.Pro
07/08/2019 14:25:19 - 			Version : [15.0,16.1]
07/08/2019 14:25:19 - 
07/08/2019 14:25:19 - 	References         : 
07/08/2019 14:25:19 - 	Prerequisites      : 
07/08/2019 14:25:19 - 		-------------------------------------------------------
07/08/2019 14:25:19 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
07/08/2019 14:25:19 - 		Name         : Visual Studio core editor
07/08/2019 14:25:19 - 		Version      : [15.0,16.1]
07/08/2019 14:25:19 - 
07/08/2019 14:25:19 - Signature Details...
07/08/2019 14:25:19 - 	Extension is not signed.
07/08/2019 14:25:19 - 
07/08/2019 14:25:19 - Searching for applicable products...
07/08/2019 14:25:19 - Found installed product - Global Location
07/08/2019 14:25:19 - Found installed product - Visual Studio Community 2019
07/08/2019 14:25:19 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jgsogo** [comment]
It looks like you are trying to install the _current version_ (the one that is currently in the Marketplace) or a development version without [this PR](https://github.com/conan-io/conan-vs-extension/pull/155) where we add support for newer versions of VS 2019 (it requires just a change in the manifest). Those `[15.0,16.1]` looks very suspicious, and I think we don't need to change anything else.

Any artifact from the `dev` branch after that PR should work for you. You can get it from Appveyor or just wait a little bit because we are planning to release a new version today/tomorrow (we need to manually run tests, so it takes some time)

**Comment by IceflowRE** [comment]
I was using this artifact: https://ci.appveyor.com/project/ConanOrgCI/conan-vs-extension/builds/26529076/job/4re87p0n57q0eiu0/artifacts

**Comment by IceflowRE** [comment]
Tried with the latest artifact, it is working, will close this when the marketplace got the update.

**Comment by jgsogo** [comment]
Thanks for trying it 👍  

The new version has been released, you can install it from the [VS marketplace](https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension) if you want.
